on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm ci
      - run: npm test -- --coverage
      - uses: codecov/codecov-action@v5
        if: ${{ always() }}
        with:
          fail_ci_if_error: true
