on:
  workflow_call:
    secrets:
      SPECTRAL_DSN:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spectralops/spectral-github-action@v5
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --fail-on-error --github-format --include-tags base,audit,iac
        env:
          SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
